apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-agent
  namespace: zabbix
rules:
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  - hostaccess
  - hostnetwork
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zabbix-agent
  namespace: zabbix
subjects:
- kind: ServiceAccount
  name: zabbix-agent
roleRef:
  kind: Role
  name: zabbix-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-agent
  namespace: zabbix