---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-proxy-mysql
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-proxy-mysql
        app: zabbix
    spec:
      volumes:
       - name: mysql-tls-certs
         secret:
           secretName: zabbix-mysql-client-tls-certs
      containers:
        - name: zabbix-proxy-mysql
          image: zabbix/zabbix-proxy-mysql:alpine-6.0-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix_proxy"
          - name: ZBX_DBTLSCONNECT
            value: "required"
          - name: ZBX_DBTLSCAFILE
            value: "/tmp/secrets/root-ca.pem"
          - name: ZBX_DBTLSCERTFILE
            value: "/tmp/secrets/client-cert.pem"
          - name: ZBX_DBTLSKEYFILE
            value: "/tmp/secrets/client-key.pem"
          - name: ZBX_DBTLSCIPHER
            value: ""
          - name: ZBX_DBTLSCIPHER13
            value: ""
          - name: ZBX_PROXYMODE
            value: "0"
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy-mysql"
          - name: ZBX_ENABLEREMOTECOMMANDS
            value: "0"
          - name: ZBX_LOGREMOTECOMMANDS
            value: "1"
          - name: ZBX_HOSTNAMEITEM
            value: ""
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_PROXYLOCALBUFFER
            value: ""
          - name: ZBX_PROXYOFFLINEBUFFER
            value: ""
          - name: ZBX_PROXYHEARTBEATFREQUENCY
            value: ""
          - name: ZBX_CONFIGFREQUENCY
            value: ""
          - name: ZBX_DATASENDERFREQUENCY
            value: ""
          - name: ZBX_STARTPOLLERS
            value: ""
          - name: ZBX_IPMIPOLLERS
            value: ""
          - name: ZBX_STARTPOLLERSUNREACHABLE
            value: ""
          - name: ZBX_STARTTRAPPERS
            value: ""
          - name: ZBX_STARTPINGERS
            value: ""
          - name: ZBX_STARTDISCOVERERS
            value: ""
          - name: ZBX_STARTHTTPPOLLERS
            value: ""
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_JAVAGATEWAY
            value: "zabbix-java-gateway"
          - name: ZBX_JAVAGATEWAYPORT
            value: "10052"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_STARTVMWARECOLLECTORS
            value: ""
          - name: ZBX_VMWAREFREQUENCY
            value: ""
          - name: ZBX_VMWAREPERFFREQUENCY
            value: ""
          - name: ZBX_VMWARECACHESIZE
            value: ""
          - name: ZBX_VMWARETIMEOUT
            value: ""
          - name: ZBX_HOUSEKEEPINGFREQUENCY
            value: ""
          - name: ZBX_CACHESIZE
            value: ""
          - name: ZBX_STARTDBSYNCERS
            value: ""
          - name: ZBX_HISTORYCACHESIZE
            value: ""
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: ""
          - name: ZBX_TIMEOUT
            value: "4"
          - name: ZBX_TRAPPERIMEOUT
            value: ""
          - name: ZBX_UNREACHABLEPERIOD
            value: ""
          - name: ZBX_UNAVAILABLEDELAY
            value: ""
          - name: ZBX_UNREACHABLEDELAY
            value: ""
          - name: ZBX_LOGSLOWQUERIES
            value: ""
          - name: ZBX_LOADMODULE
            value: ""
          - name: ZBX_TLSCONNECT
            value: ""
          - name: ZBX_TLSACCEPT
            value: ""
          - name: ZBX_TLSCAFILE
            value: ""
          - name: ZBX_TLSCRLFILE
            value: ""
          - name: ZBX_TLSSERVERCERTISSUER
            value: ""
          - name: ZBX_TLSSERVERCERTSUBJECT
            value: ""
          - name: ZBX_TLSCERTFILE
            value: ""
          - name: ZBX_TLSKEYFILE
            value: ""
          - name: ZBX_TLSPSKIDENTITY
            value: ""
          - name: ZBX_TLSPSKFILE
            value: ""
          - name: ZBX_TLSCIPHERALL
            value: ""
          - name: ZBX_TLSCIPHERALL13
            value: ""
          - name: ZBX_TLSCIPHERCERT
            value: ""
          - name: ZBX_TLSCIPHERCERT13
            value: ""
          - name: ZBX_TLSCIPHERPSK
            value: ""
          - name: ZBX_TLSCIPHERPSK13
            value: ""
          - name: DEBUG_MODE
            value: "false"
          volumeMounts:
          - mountPath: "/tmp/secrets"
            name: mysql-tls-certs
            readOnly: true
          securityContext:
            capabilities: {}
            privileged: false---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-proxy-mysql
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-proxy-mysql
        app: zabbix
    spec:
      volumes:
       - name: mysql-tls-certs
         secret:
           secretName: zabbix-mysql-client-tls-certs
      containers:
        - name: zabbix-proxy-mysql
          image: zabbix/zabbix-proxy-mysql:alpine-6.0-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix_proxy"
          - name: ZBX_DBTLSCONNECT
            value: "required"
          - name: ZBX_DBTLSCAFILE
            value: "/tmp/secrets/root-ca.pem"
          - name: ZBX_DBTLSCERTFILE
            value: "/tmp/secrets/client-cert.pem"
          - name: ZBX_DBTLSKEYFILE
            value: "/tmp/secrets/client-key.pem"
          - name: ZBX_DBTLSCIPHER
            value: ""
          - name: ZBX_DBTLSCIPHER13
            value: ""
          - name: ZBX_PROXYMODE
            value: "0"
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy-mysql"
          - name: ZBX_ENABLEREMOTECOMMANDS
            value: "0"
          - name: ZBX_LOGREMOTECOMMANDS
            value: "1"
          - name: ZBX_HOSTNAMEITEM
            value: ""
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_PROXYLOCALBUFFER
            value: ""
          - name: ZBX_PROXYOFFLINEBUFFER
            value: ""
          - name: ZBX_PROXYHEARTBEATFREQUENCY
            value: ""
          - name: ZBX_CONFIGFREQUENCY
            value: ""
          - name: ZBX_DATASENDERFREQUENCY
            value: ""
          - name: ZBX_STARTPOLLERS
            value: ""
          - name: ZBX_IPMIPOLLERS
            value: ""
          - name: ZBX_STARTPOLLERSUNREACHABLE
            value: ""
          - name: ZBX_STARTTRAPPERS
            value: ""
          - name: ZBX_STARTPINGERS
            value: ""
          - name: ZBX_STARTDISCOVERERS
            value: ""
          - name: ZBX_STARTHTTPPOLLERS
            value: ""
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_JAVAGATEWAY
            value: "zabbix-java-gateway"
          - name: ZBX_JAVAGATEWAYPORT
            value: "10052"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_STARTVMWARECOLLECTORS
            value: ""
          - name: ZBX_VMWAREFREQUENCY
            value: ""
          - name: ZBX_VMWAREPERFFREQUENCY
            value: ""
          - name: ZBX_VMWARECACHESIZE
            value: ""
          - name: ZBX_VMWARETIMEOUT
            value: ""
          - name: ZBX_HOUSEKEEPINGFREQUENCY
            value: ""
          - name: ZBX_CACHESIZE
            value: ""
          - name: ZBX_STARTDBSYNCERS
            value: ""
          - name: ZBX_HISTORYCACHESIZE
            value: ""
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: ""
          - name: ZBX_TIMEOUT
            value: "4"
          - name: ZBX_TRAPPERIMEOUT
            value: ""
          - name: ZBX_UNREACHABLEPERIOD
            value: ""
          - name: ZBX_UNAVAILABLEDELAY
            value: ""
          - name: ZBX_UNREACHABLEDELAY
            value: ""
          - name: ZBX_LOGSLOWQUERIES
            value: ""
          - name: ZBX_LOADMODULE
            value: ""
          - name: ZBX_TLSCONNECT
            value: ""
          - name: ZBX_TLSACCEPT
            value: ""
          - name: ZBX_TLSCAFILE
            value: ""
          - name: ZBX_TLSCRLFILE
            value: ""
          - name: ZBX_TLSSERVERCERTISSUER
            value: ""
          - name: ZBX_TLSSERVERCERTSUBJECT
            value: ""
          - name: ZBX_TLSCERTFILE
            value: ""
          - name: ZBX_TLSKEYFILE
            value: ""
          - name: ZBX_TLSPSKIDENTITY
            value: ""
          - name: ZBX_TLSPSKFILE
            value: ""
          - name: ZBX_TLSCIPHERALL
            value: ""
          - name: ZBX_TLSCIPHERALL13
            value: ""
          - name: ZBX_TLSCIPHERCERT
            value: ""
          - name: ZBX_TLSCIPHERCERT13
            value: ""
          - name: ZBX_TLSCIPHERPSK
            value: ""
          - name: ZBX_TLSCIPHERPSK13
            value: ""
          - name: DEBUG_MODE
            value: "false"
          volumeMounts:
          - mountPath: "/tmp/secrets"
            name: mysql-tls-certs
            readOnly: true
          securityContext:
            capabilities: {}
            privileged: false