---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web-http
  - port: 443
    targetPort: 8443
    name: web-https
  selector:
    name: zabbix-web
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10053
    targetPort: 10053
    name: zabbix-web-svc
  selector:
    name: zabbix-web-service